// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/caterings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering"
                ],
                "summary": "Returns list of caterings",
                "parameters": [
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of caterings",
                        "schema": {
                            "$ref": "#/definitions/GetCateringsResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering"
                ],
                "summary": "Returns error or 201 status code if success",
                "parameters": [
                    {
                        "description": "Catering Name",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddNameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "catering object",
                        "schema": {
                            "$ref": "#/definitions/CateringsResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering"
                ],
                "summary": "Returns info about catering",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "catering model",
                        "schema": {
                            "$ref": "#/definitions/CateringsResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering"
                ],
                "summary": "Returns 204 if success and 4xx error if failed",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Catering Name",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddNameRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully updated"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering"
                ],
                "summary": "Soft delete",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/clients": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Returns list of clients",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of clients",
                        "schema": {
                            "$ref": "#/definitions/GetClients"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "caterings clients"
                ],
                "summary": "Returns error or 201 status code if success",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Client Name",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddNameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "client object",
                        "schema": {
                            "$ref": "#/definitions/ClientsResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/clients-orders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "caterings clients"
                ],
                "summary": "Returns list of clients orders",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Date query in YYYY-MM-DDT00:00:00Z format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of clients orders",
                        "schema": {
                            "$ref": "#/definitions/swagger.GetCateringClientsSwagger"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/clients/{clientId}/categories": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering categories"
                ],
                "summary": "Get list of categories",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "clientId",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "in format YYYY-MM-DDT00:00:00Z",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "array of category readings",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/CategoryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering categories"
                ],
                "summary": "Returns error if exists and 200 if success",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "clientId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Category Name",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "category object",
                        "schema": {
                            "$ref": "#/definitions/api.Category"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/clients/{clientId}/categories/{categoryID}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering categories"
                ],
                "summary": "Returns 204 if success and 4xx error if failed",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Category ID",
                        "name": "categoryID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "new category name",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/UpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully updated"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering categories"
                ],
                "summary": "Soft delete",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "clientId",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Category ID",
                        "name": "categoryID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/clients/{clientId}/meals": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering meals"
                ],
                "summary": "GetByRange list of categories with dishes for passed meal ID",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Meal Start Date in 2020-01-01T00:00:00Z format",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "api_types": "string",
                        "description": "Meal End Date in 2020-01-01T00:00:00Z format",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "clientId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "dishes for passed day",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/GetMealsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering meals"
                ],
                "summary": "Creates meal for certain client",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "clientId",
                        "in": "path"
                    },
                    {
                        "description": "meal reading",
                        "name": "payload",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddMealRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created meal",
                        "schema": {
                            "$ref": "#/definitions/AddMealRequest"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/clients/{clientId}/orders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "caterings orders"
                ],
                "summary": "returns orders of provided client",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "clientId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Date query in YYYY-MM-DDT00:00:00Z format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Orders for clients",
                        "schema": {
                            "$ref": "#/definitions/swagger.SummaryOrdersResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/dishes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering dishes"
                ],
                "summary": "Returns list of dishes",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Category ID",
                        "name": "categoryID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of dishes",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/DishRequest"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering dishes"
                ],
                "summary": "Add dish for certain category",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "dish object",
                        "name": "payload",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddDishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "dish object",
                        "schema": {
                            "$ref": "#/definitions/DishRequest"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/dishes/{dishId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering dishes"
                ],
                "summary": "Returns dishes",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Dish ID",
                        "name": "dishId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of dishes",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/DishRequest"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering dishes"
                ],
                "summary": "Returns 204 if success and 4xx error if failed",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Dish ID",
                        "name": "dishId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dish object",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddDishRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully updated"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering dishes"
                ],
                "summary": "Soft delete",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Dish ID",
                        "name": "dishId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/dishes/{dishId}/images": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering dishes"
                ],
                "summary": "Add image for certain dish",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Dish ID",
                        "name": "dishId",
                        "in": "query"
                    },
                    {
                        "api_types": "file",
                        "description": "Image File",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "api_types": "string",
                        "description": "id of default image",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "default image",
                        "schema": {
                            "$ref": "#/definitions/ImageResponse"
                        }
                    },
                    "201": {
                        "description": "Image model",
                        "schema": {
                            "$ref": "#/definitions/ImageResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/dishes/{dishId}/images/{imageId}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering dishes"
                ],
                "summary": "Updates image for certain dish",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Image ID",
                        "name": "imageId",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Dish ID",
                        "name": "dishId",
                        "in": "path"
                    },
                    {
                        "api_types": "file",
                        "description": "Image File",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "default image",
                        "schema": {
                            "$ref": "#/definitions/ImageResponse"
                        }
                    },
                    "201": {
                        "description": "Image model",
                        "schema": {
                            "$ref": "#/definitions/ImageResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering dishes"
                ],
                "summary": "Soft delete",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Image ID",
                        "name": "imageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Dish ID",
                        "name": "dishId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/schedules": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "caterings schedules"
                ],
                "summary": "Returns list of schedules",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of schedules",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/CateringSchedule"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/caterings/{id}/schedules/{scheduleId}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "caterings schedules"
                ],
                "summary": "Returns 200 and updated model if success and 4xx error if failed",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Catering ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "CateringSchedule ID",
                        "name": "scheduleId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "CateringSchedule model",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/UpdateScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CateringSchedule model",
                        "schema": {
                            "$ref": "#/definitions/CateringSchedule"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Returns list of clients",
                "parameters": [
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of clients",
                        "schema": {
                            "$ref": "#/definitions/GetClients"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Returns info about client",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "client model",
                        "schema": {
                            "$ref": "#/definitions/ClientsResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Returns 204 if success and 4xx error if failed",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update client model",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/UpdateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully updated"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Soft delete",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/addresses": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients addresses"
                ],
                "summary": "Get list of addresses",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "array of address readings",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/AddressResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients addresses"
                ],
                "summary": "Add address for certain client",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "address object",
                        "name": "payload",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddAddressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "address object",
                        "schema": {
                            "$ref": "#/definitions/AddressResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/addresses/{addressId}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients addresses"
                ],
                "summary": "Returns 204 if success and 4xx error if failed",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Address ID",
                        "name": "addressId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "address object",
                        "name": "payload",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/AddAddressRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully updated"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients addresses"
                ],
                "summary": "Soft delete",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Address ID",
                        "name": "addressId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/auto-approve": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Returns 204 if success and 4xx error if failed",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update auto approve",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/UpdateAutoApprove"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully updated"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/order-status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients orders"
                ],
                "summary": "returns status of order",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Date query in YYYY-MM-DDT00:00:00Z format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "order status",
                        "schema": {
                            "$ref": "#/definitions/swagger.OrderStatus"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/orders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients orders"
                ],
                "summary": "returns orders of provided client",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Date query in YYYY-MM-DDT00:00:00Z format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Orders for clients",
                        "schema": {
                            "$ref": "#/definitions/swagger.SummaryOrdersResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients orders"
                ],
                "summary": "approve user orders",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Date query in YYYY-MM-DDT00:00:00Z format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully Approved orders"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients users"
                ],
                "summary": "Returns list of client users",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "api_types": "integer",
                        "description": "used for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "api_types": "string",
                        "description": "used query search",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "api_types": "string",
                        "description": "used for role sort",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "api_types": "string",
                        "description": "used for status sort",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of client users",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/swagger.UserResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients users"
                ],
                "summary": "Returns error or 201 status code if success",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "description": "Client user",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/swagger.ClientUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Client user",
                        "schema": {
                            "$ref": "#/definitions/swagger.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/users/{userId}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients users"
                ],
                "summary": "Returns error or 200 status code if success",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path"
                    },
                    {
                        "description": "Client user",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/swagger.ClientUserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Client user",
                        "schema": {
                            "$ref": "#/definitions/swagger.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients users"
                ],
                "summary": "Returns error or 204 status code if success",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/images": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catering images"
                ],
                "summary": "Returns list of images",
                "responses": {
                    "200": {
                        "description": "List of images",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/GetImagesResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/is-authenticated": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Returns user info if authorized",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Returns info about user",
                "parameters": [
                    {
                        "description": "User Credentials",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Removes cookie if set",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/orders": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users orders"
                ],
                "summary": "returns orders of provided user",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "api_types": "string",
                        "description": "Date query in YYYY-MM-DDT00:00:00Z format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Orders for user",
                        "schema": {
                            "api_types": "array",
                            "items": {
                                "$ref": "#/definitions/swagger.UserOrder"
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users orders"
                ],
                "summary": "Returns error or 201 status code if success",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Date query in YYYY-MM-DDT00:00:00Z format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "User order",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/swagger.OrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Order for user",
                        "schema": {
                            "$ref": "#/definitions/swagger.UserOrder"
                        }
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/orders/{orderId}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users orders"
                ],
                "summary": "Returns error or 204 status code if success",
                "parameters": [
                    {
                        "api_types": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "api_types": "string",
                        "description": "Order ID",
                        "name": "orderId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully canceled"
                    },
                    "400": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AddAddressRequest": {
            "api_types": "object",
            "required": [
                "city",
                "floor",
                "house",
                "street"
            ],
            "properties": {
                "city": {
                    "api_types": "string"
                },
                "floor": {
                    "api_types": "integer"
                },
                "house": {
                    "api_types": "string"
                },
                "street": {
                    "api_types": "string"
                }
            }
        },
        "AddCategoryRequest": {
            "api_types": "object",
            "required": [
                "name"
            ],
            "properties": {
                "date": {
                    "api_types": "string",
                    "example": "2020-06-29T00:00:00Z"
                },
                "name": {
                    "api_types": "string",
                    "example": "закуски"
                }
            }
        },
        "AddDishRequest": {
            "api_types": "object",
            "required": [
                "categoryId",
                "name",
                "price",
                "weight"
            ],
            "properties": {
                "categoryId": {
                    "api_types": "string"
                },
                "desc": {
                    "api_types": "string",
                    "example": "Очень вкусный"
                },
                "name": {
                    "api_types": "string",
                    "example": "грибной суп"
                },
                "price": {
                    "api_types": "number",
                    "example": 120
                },
                "weight": {
                    "api_types": "number",
                    "example": 250
                }
            }
        },
        "AddMealRequest": {
            "api_types": "object",
            "required": [
                "date",
                "dishes"
            ],
            "properties": {
                "date": {
                    "api_types": "string",
                    "example": "2020-06-20T00:00:00Z"
                },
                "dishes": {
                    "api_types": "array",
                    "items": {
                        "api_types": "string"
                    }
                }
            }
        },
        "AddNameRequest": {
            "api_types": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "api_types": "string",
                    "example": "aisnovations"
                }
            }
        },
        "AddressResponse": {
            "api_types": "object",
            "required": [
                "city",
                "floor",
                "house",
                "street"
            ],
            "properties": {
                "city": {
                    "api_types": "string"
                },
                "floor": {
                    "api_types": "integer"
                },
                "house": {
                    "api_types": "string"
                },
                "id": {
                    "api_types": "string"
                },
                "street": {
                    "api_types": "string"
                }
            }
        },
        "CategoryResponse": {
            "api_types": "object",
            "required": [
                "name"
            ],
            "properties": {
                "clientId": {
                    "api_types": "string"
                },
                "date": {
                    "api_types": "string"
                },
                "id": {
                    "api_types": "string"
                },
                "name": {
                    "api_types": "string"
                }
            }
        },
        "CateringSchedule": {
            "api_types": "object",
            "properties": {
                "day": {
                    "api_types": "integer"
                },
                "end": {
                    "api_types": "string"
                },
                "id": {
                    "api_types": "string"
                },
                "isWorking": {
                    "api_types": "boolean"
                },
                "start": {
                    "api_types": "string"
                }
            }
        },
        "CateringsResponse": {
            "api_types": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "api_types": "string"
                },
                "name": {
                    "api_types": "string"
                }
            }
        },
        "ClientsResponse": {
            "api_types": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "api_types": "string"
                },
                "name": {
                    "api_types": "string"
                }
            }
        },
        "DishRequest": {
            "api_types": "object",
            "required": [
                "name",
                "price",
                "weight"
            ],
            "properties": {
                "categoryId": {
                    "api_types": "string"
                },
                "desc": {
                    "api_types": "string"
                },
                "id": {
                    "api_types": "string"
                },
                "images": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/Image"
                    }
                },
                "name": {
                    "api_types": "string"
                },
                "price": {
                    "api_types": "number"
                },
                "weight": {
                    "api_types": "number"
                }
            }
        },
        "ErrorResponse": {
            "api_types": "object",
            "properties": {
                "code": {
                    "api_types": "integer"
                },
                "error": {
                    "api_types": "string"
                }
            }
        },
        "GetCateringsResponse": {
            "api_types": "object",
            "properties": {
                "items": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/CateringsResponse"
                    }
                },
                "page": {
                    "api_types": "integer"
                },
                "total": {
                    "api_types": "integer"
                }
            }
        },
        "GetClients": {
            "api_types": "object",
            "properties": {
                "items": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.Client"
                    }
                },
                "page": {
                    "api_types": "integer"
                },
                "total": {
                    "api_types": "integer"
                }
            }
        },
        "GetImagesResponse": {
            "api_types": "object",
            "properties": {
                "category": {
                    "api_types": "string"
                },
                "id": {
                    "api_types": "string"
                },
                "path": {
                    "api_types": "string"
                }
            }
        },
        "GetMealsResponse": {
            "api_types": "object",
            "properties": {
                "date": {
                    "api_types": "string"
                },
                "dishes": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/DishRequest"
                    }
                },
                "mealId": {
                    "api_types": "string"
                },
                "person": {
                    "api_types": "string"
                },
                "version": {
                    "api_types": "string"
                }
            }
        },
        "Image": {
            "api_types": "object",
            "properties": {
                "id": {
                    "api_types": "string"
                },
                "path": {
                    "api_types": "string"
                }
            }
        },
        "ImageResponse": {
            "api_types": "object",
            "required": [
                "path"
            ],
            "properties": {
                "id": {
                    "api_types": "string"
                },
                "path": {
                    "api_types": "string"
                }
            }
        },
        "LoginRequest": {
            "api_types": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "api_types": "string",
                    "example": "admin@meals.com"
                },
                "password": {
                    "api_types": "string",
                    "example": "Password12!"
                }
            }
        },
        "UpdateAutoApprove": {
            "api_types": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "api_types": "boolean",
                    "example": true
                }
            }
        },
        "UpdateCategoryRequest": {
            "api_types": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "api_types": "string",
                    "example": "веган"
                }
            }
        },
        "UpdateClientRequest": {
            "api_types": "object",
            "required": [
                "name"
            ],
            "properties": {
                "cateringId": {
                    "api_types": "string"
                },
                "name": {
                    "api_types": "string",
                    "example": "aisnovations"
                }
            }
        },
        "UpdateScheduleRequest": {
            "api_types": "object",
            "properties": {
                "end": {
                    "api_types": "string"
                },
                "isWorking": {
                    "api_types": "boolean"
                },
                "start": {
                    "api_types": "string"
                }
            }
        },
        "api.Category": {
            "api_types": "object"
        },
        "swagger.CateringClientSwagger": {
            "api_types": "object",
            "properties": {
                "client": {
                    "api_types": "object",
                    "$ref": "#/definitions/swagger.ClientInfo"
                },
                "ordersDishes": {
                    "api_types": "string"
                },
                "total": {
                    "api_types": "integer"
                }
            }
        },
        "swagger.Client": {
            "api_types": "object",
            "properties": {
                "autoApproveOrders": {
                    "api_types": "boolean"
                },
                "cateringId": {
                    "api_types": "string"
                },
                "cateringName": {
                    "api_types": "string"
                },
                "id": {
                    "api_types": "string"
                },
                "name": {
                    "api_types": "string"
                }
            }
        },
        "swagger.ClientInfo": {
            "api_types": "object",
            "properties": {
                "id": {
                    "api_types": "string"
                },
                "name": {
                    "api_types": "string"
                }
            }
        },
        "swagger.ClientUser": {
            "api_types": "object",
            "properties": {
                "email": {
                    "api_types": "string",
                    "example": "d.novikov@wellyes.ru"
                },
                "firstName": {
                    "api_types": "string",
                    "example": "Dmitry"
                },
                "floor": {
                    "api_types": "integer",
                    "example": 5
                },
                "lastName": {
                    "api_types": "string",
                    "example": "Novikov"
                },
                "role": {
                    "api_types": "string",
                    "example": "User"
                }
            }
        },
        "swagger.ClientUserUpdate": {
            "api_types": "object",
            "properties": {
                "email": {
                    "api_types": "string",
                    "example": "d.novikov@wellyes.ru"
                },
                "firstName": {
                    "api_types": "string",
                    "example": "Dmitry"
                },
                "floor": {
                    "api_types": "integer",
                    "example": 5
                },
                "lastName": {
                    "api_types": "string",
                    "example": "Novikov"
                },
                "role": {
                    "api_types": "string",
                    "example": "User"
                }
            }
        },
        "swagger.GetCateringClientsSwagger": {
            "api_types": "object",
            "properties": {
                "items": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.CateringClientSwagger"
                    }
                },
                "page": {
                    "api_types": "integer"
                },
                "total": {
                    "api_types": "integer"
                }
            }
        },
        "swagger.ItemsSummaryOrder": {
            "api_types": "object",
            "properties": {
                "amount": {
                    "api_types": "integer"
                },
                "name": {
                    "api_types": "string"
                }
            }
        },
        "swagger.Order": {
            "api_types": "object",
            "properties": {
                "amount": {
                    "api_types": "integer"
                },
                "dishId": {
                    "api_types": "string"
                }
            }
        },
        "swagger.OrderItem": {
            "api_types": "object",
            "properties": {
                "amount": {
                    "api_types": "integer"
                },
                "id": {
                    "api_types": "string"
                },
                "image": {
                    "api_types": "string"
                },
                "name": {
                    "api_types": "string"
                },
                "price": {
                    "api_types": "integer"
                }
            }
        },
        "swagger.OrderRequest": {
            "api_types": "object",
            "required": [
                "items"
            ],
            "properties": {
                "comment": {
                    "api_types": "string"
                },
                "items": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.Order"
                    }
                }
            }
        },
        "swagger.OrderStatus": {
            "api_types": "object",
            "properties": {
                "status": {
                    "api_types": "string"
                }
            }
        },
        "swagger.SummaryOrder": {
            "api_types": "object",
            "properties": {
                "categoryId": {
                    "api_types": "string"
                },
                "categoryName": {
                    "api_types": "string"
                },
                "items": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.ItemsSummaryOrder"
                    }
                }
            }
        },
        "swagger.SummaryOrdersResponse": {
            "api_types": "object",
            "properties": {
                "status": {
                    "api_types": "string"
                },
                "summary": {
                    "api_types": "object",
                    "$ref": "#/definitions/swagger.SummaryOrder"
                },
                "summaryTotal": {
                    "api_types": "integer"
                },
                "userOrders": {
                    "api_types": "object",
                    "$ref": "#/definitions/swagger.SummaryUserOrder"
                }
            }
        },
        "swagger.SummaryUserOrder": {
            "api_types": "object",
            "properties": {
                "comment": {
                    "api_types": "string"
                },
                "floor": {
                    "api_types": "integer"
                },
                "items": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.ItemsSummaryOrder"
                    }
                },
                "name": {
                    "api_types": "string"
                },
                "total": {
                    "api_types": "integer"
                }
            }
        },
        "swagger.UserOrder": {
            "api_types": "object",
            "properties": {
                "items": {
                    "api_types": "array",
                    "items": {
                        "$ref": "#/definitions/swagger.OrderItem"
                    }
                },
                "orderId": {
                    "api_types": "string"
                },
                "status": {
                    "api_types": "string"
                },
                "total": {
                    "api_types": "integer"
                }
            }
        },
        "swagger.UserResponse": {
            "api_types": "object",
            "properties": {
                "cateringId": {
                    "api_types": "string"
                },
                "clientId": {
                    "api_types": "string"
                },
                "companyType": {
                    "api_types": "string"
                },
                "email": {
                    "api_types": "string"
                },
                "firstName": {
                    "api_types": "string"
                },
                "floor": {
                    "api_types": "integer"
                },
                "id": {
                    "api_types": "string"
                },
                "lastName": {
                    "api_types": "string"
                },
                "role": {
                    "api_types": "string"
                },
                "status": {
                    "api_types": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "AIS Catering",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
